name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        arch: [amd64, arm, arm64, riscv64, wasm]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        env:
          CGO_ENABLED: 0
          GOOS: linux
          GOARCH: ${{ matrix.arch }}
        run: go build -v . -o fritzbox-cloudflare-dyndns

      - name: Tar up
        uses: a7ul/tar-action@v1.1.3
        with:
          command: cJ
          files: fritzbox-cloudflare-dyndns
          outPath: fritzbox-cloudflare-dyndns-${{ matrix.arch }}.tar.xz

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: fritzbox-cloudflare-dyndns-${{ matrix.arch }}
          path: fritzbox-cloudflare-dyndns-${{ matrix.arch }}.tar.xz
